apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-msprod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /ms-product
        backend:
          serviceName: ms-product-svc
          servicePort: 30002
