apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-msprod
  labels:
    name: ingress-msprod
spec:
  rules:
  - host: ?
    http:
      paths:
      - pathType: Prefix
        path: "/ms-product"
        backend:
          service:
            name: ms-product-svc
            port: 
              number: 30002
